/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as curveSol from "./Curve.sol";
export type { curveSol };
import type * as curve2Sol from "./Curve2.sol";
export type { curve2Sol };
